# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171009_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='badge',
        ),
    ]
