# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171011_1637'),
        ('registration', '0058_banlist'),
    ]

    operations = [
    ]
