# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_attendee_aslrequest'),
        ('registration', '0060_auto_20171114_1358'),
    ]

    operations = [
    ]
