# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_merge_20171225_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Event'),
            preserve_default=False,
        ),
    ]
