# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_department_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_head', to='registration.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='parentDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Department'),
        ),
    ]
